services:

  web:
    build: .
    container_name: myapp
    command: ["bash", "-c", " python /myapp/back_web/manage.py migrate
      && python /myapp/back_web/manage.py runserver 0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    environment:
      - mode=local

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx/local:/etc/nginx/template
      - .:/myapp
    ports:
      - "80:80"