"""
Django settings for auth3 project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Update the list who get code erro nfotifications
ADMINS = [('admin', 'admin@email.com')]


ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'dev-example.com']

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# development
# define additional locations
STATICFILES_DIRS = [BASE_DIR / "static"]
# production
# STATIC_ROOT = BASE_DIR / "staticfiles"