services:

  web:
    build: .
    command: python /myapp/back_web/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    environment:
      - mode=prod

  nginx:
    image: nginx:1.25.3
    restart: always
    volumes:
      - ./config/nginx/local:/etc/nginx/template
      - .:/myapp
    ports:
      - "80:80"
      - "443:443"